steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'k8s/*', 'gs://$PROJECT_ID-kubernetes-manifests/spinnaker-demo']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/spinnaker-demo:$REVISION_ID', '.']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'k8s/*', 'gs://$PROJECT_ID-kubernetes-manifests/spinnaker-demo']
- name: '${_REGISTRY}/$PROJECT_ID/helm'
  args:
    - package
    - helm
    - --app-version
    - $REVISION_ID
  id: 'helm package'
  env:
    - GCS_PLUGIN_VERSION=0.2.2
    - HELM_REPO_NAME=$_HELM_REPO_NAME
    - HELM_REPO_URL=$_HELM_REPO_URL

images: ['gcr.io/$PROJECT_ID/spinnaker-demo:$REVISION_ID']
substitutions:
 _REGISTRY: gcr.io
 _HELM_REPO_NAME: spinnakerdemo-k8s
 _HELM_REPO_URL: gs://evolvere-iot-poc-kubernetes-manifests/spinnaker-demo/charts
 _CHART_NAME: spinnakerdemo
 _ARTIFACT_URL: gs://evolvere-iot-poc-kubernetes-manifests/spinnaker-demo/charts
options:
  env:
   - SKIP_CLUSTER_CONFIG=true
   - HELM_EXPERIMENTAL_OCI=1
artifacts:
  objects:
    location: ${_ARTIFACT_URL}/
    paths:
      - ${_CHART_NAME}-$REVISION_ID.tgz


