steps:
  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    args:
      - package
      - helm
    id: 'helm package'
    env:
      - GCS_PLUGIN_VERSION=0.2.2
      - HELM_REPO_NAME=$_HELM_REPO_NAME
      - HELM_REPO_URL=$_HELM_REPO_URL

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    args:
      - plugin
      - install
      - https://github.com/mbenabda/helm-local-chart-version
      - --version
      - v0.0.7
    id: 'add version plugin'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'sh'
    args:
      - -c
      - helm local-chart-version get -c helm > $_ARTIFACT_FILENAME
    id: 'save version to artifact'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - gcloud auth application-default print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://us-west1-docker.pkg.dev
    id: 'helm login'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - helm push ${_CHART_NAME}-$(cat $_ARTIFACT_FILENAME).tgz oci://us-west1-docker.pkg.dev/$PROJECT_ID/helm-main
    id: 'helm push'

  - name: '${_REGISTRY}/$PROJECT_ID/helm'
    entrypoint: 'bash'
    args:
      - -c
      - helm gcs push ${_CHART_NAME}-$(cat $_ARTIFACT_FILENAME).tgz $_HELM_REPO_NAME
    id: 'helm push to gcs'

substitutions:
 _REGISTRY: gcr.io
 _HELM_REPO_NAME: spinnakerdemo-k8s
 _HELM_REPO_URL: gs://evolvere-iot-poc-kubernetes-manifests/spinnaker-demo/charts
 _CHART_NAME: spinnakerdemo
 _ARTIFACT_URL: gs://evolvere-iot-poc-kubernetes-manifests/spinnaker-demo/helmversion
 _ARTIFACT_FILENAME: helm-chart-version
options:
  env:
   - SKIP_CLUSTER_CONFIG=true
   - HELM_EXPERIMENTAL_OCI=1
   
artifacts:
  objects:
    location: ${_ARTIFACT_URL}/
    paths:
      - $_ARTIFACT_FILENAME
