# Default values for deis-workflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app: spinnakerdemo
namespace: spinnakerdemo-prod
selectorLabels: spinnakerdemo
replicaCount: 1
configMap: sampleapp-config-prod

image:
  repository: gcr.io/evolvere-iot-poc/spinnaker-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: LoadBalancer
  port: 80


